extern const GeoLayout ssl_area_1_geo[];
extern const GeoLayout ssl_area_1[];
extern const Collision ssl_area_1_collision[];
extern const MacroObject ssl_area_1_macro_objs[];
extern Lights1 ssl_dl_f3dlite_material_004_lights;
extern Lights1 ssl_dl_f3dlite_material_003_lights;
extern Lights1 ssl_dl_f3dlite_material_005_lights;
extern Lights1 ssl_dl_f3dlite_material_lights;
extern Lights1 ssl_dl_f3dlite_material_001_lights;
extern u8 ssl_dl_shitty_fence_rgba16[];
extern u8 ssl_dl_checker_ci4[];
extern u8 ssl_dl_checker_ci4_pal_rgba16[];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_0[26];
extern Gfx ssl_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_1[52];
extern Gfx ssl_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_2[34];
extern Gfx ssl_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_3[10];
extern Gfx ssl_dl_Plane_mesh_layer_1_tri_3[];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_4[4];
extern Gfx ssl_dl_Plane_mesh_layer_1_tri_4[];
extern Gfx mat_ssl_dl_f3dlite_material_004[];
extern Gfx mat_ssl_dl_f3dlite_material_003[];
extern Gfx mat_ssl_dl_f3dlite_material_005[];
extern Gfx mat_ssl_dl_f3dlite_material[];
extern Gfx mat_ssl_dl_f3dlite_material_001[];
extern Gfx mat_revert_ssl_dl_f3dlite_material_001[];
extern Gfx ssl_dl_Plane_mesh_layer_1[];
extern Gfx ssl_dl_material_revert_render_settings[];
