extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern Lights1 ccm_dl_f3dlite_material_lights;
extern Lights1 ccm_dl_f3dlite_material_001_lights;
extern u8 ccm_dl_smile2_ci8[];
extern u8 ccm_dl_smile2_ci8_pal_rgba16[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_0[77];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Plane_mesh_layer_4_vtx_0[4];
extern Gfx ccm_dl_Plane_mesh_layer_4_tri_0[];
extern Gfx mat_ccm_dl_f3dlite_material[];
extern Gfx mat_ccm_dl_f3dlite_material_001[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_001[];
extern Gfx ccm_dl_Plane_mesh_layer_1[];
extern Gfx ccm_dl_Plane_mesh_layer_4[];
extern Gfx ccm_dl_material_revert_render_settings[];
