extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_f3dlite_material_lights;
extern Lights1 bob_dl_f3dlite_material_001_lights;
extern u8 bob_dl_tlbase_rgba16[];
extern u8 bob_dl_trbase_rgba16[];
extern u8 bob_dl_brbase_rgba16[];
extern u8 bob_dl_blbase_rgba16[];
extern u8 bob_dl_smile_rgba16[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[10];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_1[29];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_2[4];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_3[4];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_4[4];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_4[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_5[4];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_5[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_6[4];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_6[];
extern Gfx mat_bob_dl_f3dlite_material[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx mat_bob_dl_f3dlite_material_002[];
extern Gfx mat_bob_dl_f3dlite_material_003[];
extern Gfx mat_bob_dl_f3dlite_material_005[];
extern Gfx mat_bob_dl_f3dlite_material_004[];
extern Gfx mat_bob_dl_f3dlite_material_006[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
