extern const GeoLayout castle_inside_area_1_geo[];
extern const GeoLayout castle_inside_area_1[];
extern const Collision castle_inside_area_1_collision[];
extern const MacroObject castle_inside_area_1_macro_objs[];
extern Lights1 castle_inside_dl_f3dlite_material_lights;
extern Lights1 castle_inside_dl_f3dlite_material_001_lights;
extern Lights1 castle_inside_dl_f3dlite_material_007_lights;
extern u8 castle_inside_dl_BETA_BRICKS_rgba32[];
extern u8 castle_inside_dl_smile_rgba16[];
extern u8 castle_inside_dl_beTHA_MAR_ci4[];
extern u8 castle_inside_dl_beTHA_MAR_ci4_pal_rgba16[];
extern Vtx castle_inside_dl_Plane_mesh_layer_1_vtx_0[28];
extern Gfx castle_inside_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_Plane_mesh_layer_1_vtx_1[26];
extern Gfx castle_inside_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx castle_inside_dl_Plane_mesh_layer_1_vtx_2[4];
extern Gfx castle_inside_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx castle_inside_dl_Plane_mesh_layer_1_vtx_3[52];
extern Gfx castle_inside_dl_Plane_mesh_layer_1_tri_3[];
extern Gfx mat_castle_inside_dl_f3dlite_material[];
extern Gfx mat_castle_inside_dl_f3dlite_material_001[];
extern Gfx mat_revert_castle_inside_dl_f3dlite_material_001[];
extern Gfx mat_castle_inside_dl_f3dlite_material_006[];
extern Gfx mat_castle_inside_dl_f3dlite_material_007[];
extern Gfx mat_revert_castle_inside_dl_f3dlite_material_007[];
extern Gfx castle_inside_dl_Plane_mesh_layer_1[];
extern Gfx castle_inside_dl_material_revert_render_settings[];
