extern const GeoLayout pss_area_1_geo[];
extern const GeoLayout pss_area_1[];
extern const Collision pss_area_1_collision[];
extern const MacroObject pss_area_1_macro_objs[];
extern Lights1 pss_dl_f3dlite_material_lights;
extern Lights1 pss_dl_f3dlite_material_004_lights;
extern Lights1 pss_dl_f3dlite_material_005_lights;
extern Lights1 pss_dl_f3dlite_material_006_lights;
extern Lights1 pss_dl_f3dlite_material_002_lights;
extern Vtx pss_dl_Plane_mesh_layer_1_vtx_0[248];
extern Gfx pss_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx pss_dl_Plane_mesh_layer_1_vtx_1[38];
extern Gfx pss_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx pss_dl_Plane_mesh_layer_1_vtx_2[16];
extern Gfx pss_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx pss_dl_Plane_mesh_layer_1_vtx_3[16];
extern Gfx pss_dl_Plane_mesh_layer_1_tri_3[];
extern Vtx pss_dl_Plane_001_mesh_layer_1_vtx_0[907];
extern Gfx pss_dl_Plane_001_mesh_layer_1_tri_0[];
extern Gfx mat_pss_dl_f3dlite_material[];
extern Gfx mat_pss_dl_f3dlite_material_004[];
extern Gfx mat_pss_dl_f3dlite_material_005[];
extern Gfx mat_pss_dl_f3dlite_material_006[];
extern Gfx mat_pss_dl_f3dlite_material_002[];
extern Gfx pss_dl_Plane_mesh_layer_1[];
extern Gfx pss_dl_Plane_001_mesh_layer_1[];
extern Gfx pss_dl_material_revert_render_settings[];
