extern const GeoLayout bbh_area_1_geo[];
extern const GeoLayout bbh_area_1[];
extern const Collision bbh_area_1_collision[];
extern const MacroObject bbh_area_1_macro_objs[];
extern Lights1 bbh_dl_f3dlite_material_lights;
extern u8 bbh_dl_romestone_fixed_i8[];
extern Vtx bbh_dl_Plane_mesh_layer_1_vtx_0[2262];
extern Gfx bbh_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_bbh_dl_f3dlite_material[];
extern Gfx bbh_dl_Plane_mesh_layer_1[];
extern Gfx bbh_dl_material_revert_render_settings[];
